---
title: "Final-Project-Proposal"
author: "Wenyu Zhang"
date: "11/12/2021"
output: github_document
---
## Welcome to New York!

### Group member (names and UNIs)
Shiwei Chen - sc4935

Shiyin (Fiona) Li - sl5010

Weize Sun - ws2646

Wenyu Zhang - wz2591

Yiming Li - yl4925

### The tentative project title

Risky NYC

### The motivation for this project
In the 1980s, New York was one of the most crime-ridden cities in the United States. From the 1990s to the 2010s, the crime rate of NYC dropped sharply. Nowadays, NYC has become one of the lowest crime rates of major cities in the US.

As the brand new residents of NYC, we would like to explore the security situation and stability of this city. In addition, analyzing crime data from NYPD might raise the safety awareness of the victim population as well as other citizens and visitors, thus they can avoid high-crime areas.

Finally, our project also could provide housing and daily travel advice to our classmates and alumni.

### The intended final products
Our intended final product should be a website that includes the crime reports for each of the five boroughs of NYC from 2006 to the present. 

From the reports, we want to see the yearly trends of crime rate and the distribution of crime levels in the whole city and specific areas respectively and do the prediction for the next few years.

Moreover, counting the types of victims and the frequency of crime in different premises, and doing statistics on the time of day and the month of the year with the highest crime rate as well.

### The anticipated data sources
The data was collected from NYC open data, which is about NYPD Complaint Data Historic. This dataset includes all valid felony, misdemeanor, and violation crimes reported to the New York City Police Department (NYPD) from 2006 to the end of last year (2019). The data was collected annually. The dataset has 7.38M rows and 35 variables, each row is a complaint.

### The planned analyses/visualizations/coding challenges
Firstly, the analyses would be performed on the crime distribution of the district, and an interactive map would be generated. Then the analysis of information (age, gender, race) of the victim would also be performed, and the bar chart would also be used to visualize the result. Furthermore, linear regression would be performed, and it would be used to predict the crime rate for each distribution in the next couple of years. Since the dataset has 7,375,993 datas, it is challenging to tidy such a large dataset. 

### The planned timeline
11/13/2021 - 11/15/2021: tidy the data

11/16/2021 - 11/22/2021: perform the visualizations and analysis

11/23/2021 - 11/28/2021: doing linear regression and prediction

11/29/2021 - 12/05/2021: writing discussion and background

12/06/2021 - 12/10/2021: doing webpage and screencast

12/11/2021 - check again and finish the final report


-------------------------------------------------------

Clean the data



